export const SET_COUNTRIES = 'SET_COUNTRIES';
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const GET_CARDS_DATA = 'GET_CARDS_DATA';
export const SET_LINE_CHART_DATA = 'SET_LINE_CHART_DATA';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const CHANGE_SELECTED_CARD = 'CHANGE_SELECTED_CARD';
export const RESET_MAP = 'RESET_MAP';
